# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0002_auto_20170120_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cippoint',
            name='EstConFnDt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cippoint',
            name='EstConStDt',
            field=models.DateField(),
        ),
    ]
