# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0003_auto_20170121_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cippoint',
            name='EstConFnDt',
        ),
        migrations.RemoveField(
            model_name='cippoint',
            name='EstConStDt',
        ),
    ]
