# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 00:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0004_auto_20170121_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('queryTime', models.DateTimeField()),
                ('url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('bureau', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIimports.ApiElement')),
            ],
        ),
    ]
