# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0004_auto_20170414_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='canonical_status',
            field=models.CharField(default='', max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='orig_status',
            field=models.CharField(default='', max_length=2083, null=True),
        ),
    ]
