# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0005_apielement_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='apielement',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=2083),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apielement',
            name='queryTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
