# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 21:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0005_auto_20170414_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('name', models.CharField(max_length=2083)),
                ('label', models.CharField(max_length=2083)),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='neighborhood',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='APIimports.Neighborhood'),
        ),
    ]
