# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 20:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0006_auto_20170201_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIPline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrjNumSAP', models.CharField(max_length=1000)),
                ('PrjName', models.CharField(max_length=1000)),
                ('Status', models.CharField(max_length=1000)),
                ('Comments', models.CharField(max_length=1000)),
                ('Program', models.CharField(max_length=1000)),
                ('FundSrc', models.CharField(max_length=1000)),
                ('EstCost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Bureau', models.CharField(max_length=1000)),
                ('Contact', models.CharField(max_length=1000)),
                ('Geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
