# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 21:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0006_auto_20170415_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='canonical_daterange',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='orig_daterange',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
    ]
