# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 02:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0007_auto_20170210_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
