# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0008_auto_20170210_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='dateRange',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
