# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0009_point_daterange'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='data',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='point',
            name='sourceRef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APIimports.ApiElement'),
        ),
    ]
