# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0008_stpjline'),
        ('APIimports', '0010_auto_20170210_0248'),
    ]

    operations = [
    ]
