# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0011_merge_20170210_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='data',
            field=models.TextField(default=None),
        ),
    ]
