# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIimports', '0016_auto_20170310_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apielement',
            old_name='name',
            new_name='apiName',
        ),
        migrations.RemoveField(
            model_name='line',
            name='projectName',
        ),
        migrations.RemoveField(
            model_name='point',
            name='projectName',
        ),
        migrations.RemoveField(
            model_name='polygon',
            name='projectName',
        ),
        migrations.AddField(
            model_name='apielement',
            name='projectName',
            field=models.CharField(default='temp', max_length=2083),
            preserve_default=False,
        ),
    ]
