#! /bin/bash -v

cd ..
source venv/bin/activate

# Create the database structure
cd transDjango
./manage.py migrate
./manage.py createcachetable

# Import the neighborhood boundaries

./manage.py load_neighborhoods

# Download API json files to the database
./manage.py import_jsons

# Copy data to the main geometry tables that are connected to the API
./manage.py ingest_jsons

# Convert local CSV data into geojson and load them to the main geometry tables
./manage.py ingest_csvs

# Load local geojson data (converted from City of Portland shapefiles). Warning: BIG FILE!
./manage.py ingest_local_jsons

# In order for the conflict api to work, you'll need to precalculate the pairwise comparisons of the features:
./manage.py buildGraphs

# document schema
postgresql_autodoc -d transdev -t html
